### ISSUE TITLE
TenneseeEastman dataset Dataframe and GroundTruth shape issue

### ISSUE THREAD

**Issue by MHassaanButt** [giovanniMen/CPCaD-Bench#1]
Hi, 

I hope you are doing well. I tried to reproduce your paper results and while loading the dataset I see an issue your data frame has 32 columns actually, in reality, it's 31 first unnamed is the index column.

`Index(['Unnamed: 0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9',
       'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19',
       'X20', 'X21', 'X22', 'X23', 'X24', 'X25', 'X26', 'X28', 'X29', 'X30',
       'X32', 'X33'],
      dtype='object')`

But your Groundtruth in the txt file has (33,33) shape which is mismatched in terms to evaluate model performance. I crossed checked your dataset txt same issue was found there as well shape is 31 (excluded index). Could you please share the correct dataset files? Thanks!

**Comment by giovanniMen** [comment]
Hi, check out variables name. It's likely that i dropped empty columns that do not have causal effect. Just try to remove from gt empty  rows.

**Comment by MHassaanButt** [comment]
Hi, thank you for your response, In your columns you already don't have X27 and X31. As you said to remove empty rows from GT. If empty is for you are those rows that have all values zero then in that case we have multiple rows in your GT i.e, index=[16,18,20,28,31,33] which again mismatched the data frame and Groundtruth shape. Can you share the exact ground-truth and data frame files that you used for model evaluation? or the preprocessed one. Thanks!

**Comment by giovanniMen** [comment]
Hi, sorry for the late answer!
Have you tried removing line/column 27 and 31 from the GT so that your shape will match the data? Were you able to replicate the results? 
Also you can check distributions or the original TE dataset that is cited in the paper to double check. 
The GT I used is the one i uploaded. If need I can check the code (have to restore a backup)

**Comment by MHassaanButt** [comment]
Thank you its work for me
