### ISSUE TITLE
TE dataset anomaly issue

### ISSUE THREAD

**Issue by AMBITIQN** [giovanniMen/CPCaD-Bench#2]
Sorry to bother you sir, I have a question regarding the TE dataset in the project. The TE dataset loaded in the original paper contains 33 nodes, but the data of two nodes are missing in the original statistical data file given, which are X27 & X31.May I ask if it is possible to request a complete copy of the TE dataset used in the original paper from you to be used as a benchmark for the subsequent development of the causal discovery method?

**Comment by giovanniMen** [comment]
Hi AMBITIQN, as I wrote in the paper I removed variables with null variance. Are you referring to those? 
Have you access to the paper? 
Bye

**Comment by AMBITIQN** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
